# Generated by Django 4.2.15 on 2024-08-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
