# Generated by Django 3.2.19 on 2024-08-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_alter_posts_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
